name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      image_uri:
        description: 'Full container image URI (e.g. 123456.dkr.ecr.us-east-1.amazonaws.com/tm-app:abc123)'
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Write terraform.auto.tfvars
        run: |
          echo 'container_image    = "${{ github.event.inputs.image_uri }}"' > terraform/terraform.auto.tfvars
          echo 'cloudflare_zone_id = "${{ secrets.CLOUDFLARE_ZONE_ID }}"' >> terraform/terraform.auto.tfvars
          echo 'cloudflare_api_key = "${{ secrets.CLOUDFLARE_API_KEY }}"' >> terraform/terraform.auto.tfvars
          echo 'domain_name        = "${{ secrets.DOMAIN_NAME }}"' >> terraform/terraform.auto.tfvars

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: tflint --init && tflint

      - name: Run Checkov (unless SKIP_CHECKOV is true)
        if: ${{ vars.SKIP_CHECKOV != 'true' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file=terraform.auto.tfvars

      - name: Upload tfvars for apply/destroy
        uses: actions/upload-artifact@v4
        with:
          name: terraform-vars
          path: terraform.auto.tfvars
