name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      image_uri:
        description: 'Full container image URI (e.g. 123456.dkr.ecr.us-east-1.amazonaws.com/tm-app:abc123)'
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: tflint --init && tflint

      - name: Run Checkov (unless SKIP_CHECKOV is true)
        if: ${{ vars.SKIP_CHECKOV != 'true' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="container_image=${{ github.event.inputs.image_uri }}" \
            -var="cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}" \
            -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}"
