name: Terraform Plan

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  terraform-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get ECR URI
        id: ecr
        run: |
          URI=$(aws ecr describe-repositories --repository-names tm-app --query 'repositories[0].repositoryUri' --output text)
          echo "ECR_URI=$URI" >> $GITHUB_ENV
          echo "IMAGE_URI=$URI:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: tflint --init && tflint

      - name: Run Checkov (unless SKIP_CHECKOV is true)
        if: ${{ vars.SKIP_CHECKOV != 'true' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform

      - name: Terraform Plan and Save to File
        working-directory: ./terraform
        run: |
          terraform plan \
            -out=tfplan.binary \
            -var="container_image=${{ env.IMAGE_URI }}" \
            -var="cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}" \
            -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}"

      - name: Upload Terraform Plan File
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan.binary
